### ISSUE TITLE
Duplicate confirm dialog when delete a draft

### ISSUE THREAD

**Issue by J2TEAM** [Kipalog/Issue-tracker#10]
![Kipalog](https://i.imgur.com/U45Ej2u.gif)

**Comment by orakaro** [comment]
Mình không tái hiện được bug này :( Bạn có thể cho biết 
- Browser đang dùng
- Version của browser
- OS đang dùng
  được không ? Many thanks !

**Comment by J2TEAM** [comment]
:grinning: 
- Browser: Chrome v46.0.2490.80
- OS: Windows 7 (x86)

``` js
console.log(navigator.userAgent)

// Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36
```

**Comment by orakaro** [comment]
Trên cùng phiên bản (46.0.2490.80) với Window7 64bit cũng không tái hiện được :(

Bạn thử giúp mình refresh page hoặc tắt đi vào lại xem lỗi có thường xuyên xảy ra không được không ?

**Comment by J2TEAM** [comment]
Mình vừa thử lại ở chế độ ẩn danh thì thấy không bị, không biết bị sao nữa :confused:

Có lẽ là do một extension nào đó tác động vào trang (vì mặc định thì các extension không kích hoạt trên chế độ ẩn danh).

**Comment by orakaro** [comment]
Thanks :smile:
