### ISSUE TITLE
Error when loading page

### ISSUE THREAD

**Issue by tranductam2802** [Kipalog/Issue-tracker#12]
Step 1: Connect to kipalog
Step 2: View display content

![image](https://cloud.githubusercontent.com/assets/4957579/10927961/b95581c0-82d6-11e5-95f9-b160ab6783bf.png)

**Comment by orakaro** [comment]
Hi bạn. Có lẽ là network không ổn định nên Javascript không load được. Bạn đợi 1 thời gian thử lại hoặc đổi network xem có bị không ?
