### ISSUE TITLE
Un-publish

### ISSUE THREAD

**Issue by cavoirom** [Kipalog/Issue-tracker#13]
Nay mình lỡ tay bấm đăng bài viết nhưng chưa thật sự hoàn thiện, mình không thấy cách nào để lưu nó thành bản nháp nữa. Nên có chức năng chuyển bài đã đăng thành nháp trong trường hợp tương tự, nếu không sẽ phải copy nội dung bài viết đó, tạo bản nháp, xóa bài viết cũ, rất mất công.

**Comment by orakaro** [comment]
Cảm ơn bạn, đúng là cần tính năng này thật. Bọn mình sẽ lên kế hoạch update!
