### ISSUE TITLE
Không thể đọc notification

### ISSUE THREAD

**Issue by hieudoan-ew** [Kipalog/Issue-tracker#16]
Click link này trong thông báo: http://kipalog.com/posts/JAVA-Socket-Q-A-help-please-----

Báo lỗi 500.

**Comment by orakaro** [comment]
@hieudoan-ew Cảm ơn bạn team sẽ check và fix !

**Comment by hieudoan-ew** [comment]
Minh nghĩ nguyên nhân là do user đổi tên bài viết hoặc xóa bài viết thì sẽ gây ra lỗi này. Hi vọng thông tin này sẽ hữu ích.

**Comment by orakaro** [comment]
Mình cũng nghĩ như trên. Bài viết này thì có lẽ là đã bị xóa. Thanks!
