### ISSUE TITLE
Tự động xuống dòng

### ISSUE THREAD

**Issue by smilekid1994** [Kipalog/Issue-tracker#18]
Mình viết markdown text bằng vim (bật auto split line) nên bị xuống dòng, bài viết nhìn không đẹp. Bình thường markdown sẽ chỉ nhận xuống dòng khi có 1 dòng trống. Có cách nào để điều chỉnh vấn đề này không nhỉ?

> ádfaadsfadsf
> adsfasdfasdf

sẽ hiển thị 1 dòng

> adsfasdf
> 
> ádfasdf

sẽ hiển thị xuống xòng

**Comment by orakaro** [comment]
Hi bạn, ý bạn là làm thế nào để không cần thêm 1 dòng trống ở giữa mà vẫn xuống dòng bình thường đúng không nhỉ ?

**Comment by thangngoc89** [comment]
Nói chung là theo chuẩn Commonmark là ổn. Mình copy bài từ blog qua phải sửa rất mệt

**Comment by orakaro** [comment]
Hi bạn, Trước kia Kipalog cũng dùng newline theo chuẩn Markdown, tuy nhiên sau khi có 1 số bạn phàn nàn khó viết + khó nhìn thì đã chuyển qua GFM-style line breaks như hiện tại. Phần này có lẽ bọn mình sẽ khó có thể move lại như cũ, bạn thông cảm :)

Nếu sửa bất tiện quá thì sau khi move bài viết qua bạn để trong draft rồi thông báo cho bọn mình, bọn mình sẽ giúp bạn :beer:

**Comment by thangngoc89** [comment]
Cảm ơn bạn đã reply. Thật sự thì newline chuẩn common mark rất là tiện lợi khi viết trong một editor không có auto wrap. (Đúng tinh thần của markdown là chỉ cần đọc raw cũng đã nắm bắt được cấu trúc và nội dung)

> Nếu sửa bất tiện quá thì sau khi move bài viết qua bạn để trong draft rồi thông báo cho bọn mình, bọn mình sẽ giúp bạn 

Không cần đâu. Mình đã có script để làm việc này

Chỉ đơn giản là replace `\n` thành `\s`. Và đừng replace cái nào có `\n\n`

**Comment by orakaro** [comment]
:+1:
