### ISSUE TITLE
RSS feed???

### ISSUE THREAD

**Issue by xuta** [Kipalog/Issue-tracker#2]
## Không phải issue nhá, nhưng ko biết gửi ý kiến ở đâu :D.

Tôi thấy nên có thêm RSS, chia ra làm vài link
- tất cả bài viết
- kho log của tôi
- nhóm theo 1 số chủ đề (hashtag, ...)

Tôi dùng feedly để đọc tin tức công nghệ và chắc nhiều người khác cũng làm thế. Nên nếu làm việc với RSS sẽ thuận tiện hơn nhiều.

Thanks,

**Comment by orakaro** [comment]
Cảm ơn bạn @xuta . Đúng là có RSS sẽ tiện hơn cho các bạn đọc tin tức dạng feed. Team sẽ cho RSS vào kế hoạch phát triển trong tương lai !

**Comment by giautm** [comment]
Hi! Mình dùng Nextgen Reader để đọc RSS. Các bạn có thể bổ sung chức năng cho site sớm được không.
Có hai lý do để mình đề nghị điều này.
1. Mình lười login site trên mọi thiết bị để check bài viết mới. RSS reader sẽ tự check và tạo thông báo.
2. Response của site trên windows phone khá cùi bắp. Lúc thì có thể tự co, lúc thì tràn hết ra bên phải.

Cám ơn team. :)

**Comment by orakaro** [comment]
Cảm ơn bạn, để bọn mình cân nhắc về RSS. Xin lỗi về sự bất tiện nhưng hiện tại Kipalog chưa có ý định support design trên window phone. Bạn có thể thử dùng một trình duyệt khác ngoài trình duyệt mặc định (IE) trên windowphone và feedback lại cho team được không? Many thanks!

**Comment by huydx** [comment]
done

**Comment by jaredchu** [comment]
**Done** nhưng rốt cục link rss của Kipalog nằm ở đâu? Xin lỗi vì kiến thức hạn hẹp nhưng thường thì các website sẽ có tag `<link rel="alternate" type="application/rss+xml" title="RSS Feed" href="http://example.org/rss" />` nhưng mình không tìm thấy tag này trên kipalog.

**Comment by vietstone-ng** [comment]
Vậy là có rss feed chưa nhỉ?

**Comment by orakaro** [comment]
@jaredchu @vietstone ở trong trang cài đặt. Tuy vậy cần phải viết 2 bài trở lên mới có thể nhìn thấy link RSS 😄 . Cheer
