### ISSUE TITLE
Hiện ngày đăng bài

### ISSUE THREAD

**Issue by ngocdaothanh** [Kipalog/Issue-tracker#20]
Mình cần tính năng này, để khi xem lại (vài năm sau chẳng hạn) sẽ biết mình viết vào lúc nào.

**Comment by huydx** [comment]
@ngocdaothanh hiện bọn em đã cho hiện ngày created_at rồi, có phải ý anh là ngày cụ thể thay vì normalize nó lại dưới dạng [xxx ngày trước] không anh ?

**Comment by ngocdaothanh** [comment]
Chỉ cho mình chỗ nó hiện được không?
Ví dụ trong screenshot này mình k thấy:

<img width="927" alt="screen shot 2016-04-09 at 6 29 41 am" src="https://cloud.githubusercontent.com/assets/10095/14396718/93073132-fe1c-11e5-90fb-f0d25825545e.png">

**Comment by huydx** [comment]
Hiện bọn em đang cho hiện ở list view thay vì view từng bài viết.
Nếu là bài viết của anh anh có thể xem tại trang mypage của cá nhân.
Không biết thông tin ở view này đã đủ cho mục đích 

> để khi xem lại (vài năm sau chẳng hạn) sẽ biết mình viết vào lúc nào

không anh

![](https://i.gyazo.com/038240db4b759a54b39697db7dfabe74.png)

**Comment by ngocdaothanh** [comment]
Mình vẫn thích ở từng bài có hiện thời điểm đăng bài.
Ví dụ khi chia sẻ bài viết cho người khác, người khác sẽ vào thẳng bài viết.

Cột bên phải còn rất của trang hiện bài viết còn rất trống trải.
Hiện thêm thông tin trên thì có gì đâu nhỉ.

**Comment by huydx** [comment]
@ngocdaothanh ok anh em hiểu rồi, bọn em sẽ xem nên thêm vào view thế nào rồi thêm vào nhé.

**Comment by ngocdaothanh** [comment]
:+1:

**Comment by orakaro** [comment]
Hi anh @ngocdaothanh, bọn em vừa thêm ngày tháng vào phía bên trên (dưới title và tag) rồi ạ!
