### ISSUE TITLE
Tối ưu cho việc xem trên di động

### ISSUE THREAD

**Issue by tam-pham-alpha** [Kipalog/Issue-tracker#21]
Hiện tại việc xem kipalog trên di động vẫn chưa được tốt lắm

**Comment by orakaro** [comment]
Hi - bạn có thể cho biết cụ thể hơn chưa tốt ở page nào được không, nếu có screenshot thì càng tốt :D

**Comment by tam-pham-alpha** [comment]
Khi dzo trang chi tiết thì layout bị vỡ, muốn coi được thì mình phải scroll ngang qua, hay là zoom web nhỏ lại. Mình duyệt web trên windowphone.
![wp_ss_20160410_0001](https://cloud.githubusercontent.com/assets/5687992/14409887/4109f840-ff4a-11e5-9920-873613802bd8.png)
![wp_ss_20160410_0002](https://cloud.githubusercontent.com/assets/5687992/14409888/410a0bf0-ff4a-11e5-988e-c2f6dfe9343b.png)
![wp_ss_20160410_0003](https://cloud.githubusercontent.com/assets/5687992/14409889/410cc0ca-ff4a-11e5-804c-7c4cc603c051.png)

**Comment by orakaro** [comment]
Thanks @tampham47 

Hiện tại Default browser trên WindowPhone và IE trên Desktop không nằm trong kế hoạch support của Kipalog. Mình xin lỗi vì sự bất tiện nhưng bạn có thể dùng browser khác cho Windowphone và nhắn lại kết quả cho team được không. Cảm ơn bạn :)

**Comment by tam-pham-alpha** [comment]
@DTVD mình dùng UC Browser trên window phone vẫn gặp lỗi tương tự :((

**Comment by orakaro** [comment]
Hi @tampham47 

Mình vừa thử dùng UC Browser trên ... iPhone cùng bài viết nhưng không thấy vấn đề gì. Phiền bạn có thể cho thêm thông tin như ở dưới đây được không ?
1. Tất cả các bài viết bị lỗi hay chỉ mình bài trên. (Default browser / UC Browser)
2. Điểm chung dễ thấy của các bài lỗi (nếu có)
3. Model cua WindowPhone
4. Windowphone có thể install được Chrome hay không , nếu có nhờ bạn thử dùng Chrome.xem sao :)

Many thanks !

**Comment by tam-pham-alpha** [comment]
Hi @DTVD 

Hiện tại mình dùng windowphone 8.1.
Theo mình thấy thì chỉ có trang chi tiết bị bể layout thôi, width của trang chi tiết bị ảnh hưởng bởi with của các hình ảnh ở trong bài viết, hình ảnh không tự động scale xuống cho phù hợp với kích thước màn hình.

PS/ Header của trang chi tiết hiển thị tốt, chỉ có phần nội dung là bị vỡ thôi.

**Comment by orakaro** [comment]
Cảm ơn bạn @tampham47. Mình có thể đoán được vấn đề nằm ở max-width của image.

Tuy vậy windowphone 8.1 cũng có 1 vấn đề với viewport nữa và hiện giờ team hiện không có window phone để test nên rất khó để chữa lỗi. Rất xin lỗi bạn vì sự bất tiện này. Đến khi nào bọn mình có thể support được WindowPhone bọn mình sẽ thông báo lại với bạn nhé !

**Comment by orakaro** [comment]
Hi @tampham47. Kipalog vừa release một batch sửa được lỗi image, tuy vậy không có window phone để test. Phiền bạn có thể check lại hộ bọn mình được không?

**Comment by tam-pham-alpha** [comment]
@DTVD ok, mình sẽ kiểm tra rồi báo lại sớm :))
