### ISSUE TITLE
[Feature request] Signature

### ISSUE THREAD

**Issue by J2TEAM** [Kipalog/Issue-tracker#22]
Mỗi lần đăng bài mình phải tự copy lại phần footer từ bài trước đó qua nên hơi phiền. Hi vọng Kipalog team có thể cập nhật thêm tính năng chữ ký thì tốt quá :+1:

![image](https://cloud.githubusercontent.com/assets/5250117/14629819/816bd4b8-0633-11e6-8cc8-b5ea27141046.png)

**Comment by orakaro** [comment]
Cái này mark thành Template for user nhỉ @huydx

**Comment by huydx** [comment]
@J2TeaM ok bạn, bọn mình sẽ xem xét để thêm tính năng này, cũng là một tính năng khá thú vị
