### ISSUE TITLE
Update Github link in Profile 

### ISSUE THREAD

**Issue by duyet** [Kipalog/Issue-tracker#23]
Hiện Github link của mình có thay đổi, nhưng trong trang cá nhân không có chỗ để thay đổi link này, thank :)

http://kipalog.com/users/duyetdev/mypage

**Comment by orakaro** [comment]
Hi @duyetdev, hiện tại Kipalog chưa để người dùng có thể update social profile. Mình vừa tự sửa lại thành đường link đúng - bạn check nhé!

**Comment by duyet** [comment]
Thanks anh :smile:
