### ISSUE TITLE
Module tự động tạo đầu mục?

### ISSUE THREAD

**Issue by manhhailua** [Kipalog/Issue-tracker#26]
Mình thấy chức năng tự động tạo đầu mục cho bài viết dựa trên markdown của Kipalog rất hay và đang muốn áp dụng cho website cá nhân. Không rõ Kipalog thực hiện điều đó như thế nào hay đang sử dụng module nào?

**Comment by orakaro** [comment]
Bọn mình dùng code-mirror editor nên chức năng đấy là 1 phần của code-mirror bạn ạ :smile:
