### ISSUE TITLE
email bị trùng

### ISSUE THREAD

**Issue by ghost** [Kipalog/Issue-tracker#27]
mail: trunghieu.7393@gmail.com

mình không nhớ là đã đăng ký dựa trên github hay đơn thuần là email.

giờ mình không thể đăng nhập vào, mình k thấy chức năng reset password.

giờ mình tạo mới dựa trên github cũng bị lỗi email đã tồn tại.

mong admin check lại email của mình, bạn có thể gửi mail để mình xác minh.

**Comment by orakaro** [comment]
Hi bạn, bạn có thể gửi mail đến kipalog.com@gmail.com được không, team sẽ reset lại password và trả lời vào mail trên!
