### ISSUE TITLE
Tùy chỉnh kích thước hình ảnh

### ISSUE THREAD

**Issue by ghost** [Kipalog/Issue-tracker#28]
Cảm ơn Kipalog đã hỗ trợ mình về tài khoản.
mình viết bài thì gặp vấn đề thế này, hình ảnh mình import vào thì hơi lớn có cách nào để tuỳ chỉnh kích thước hình ảnh bằng markdown không?

**Comment by orakaro** [comment]
Hiện tại thì bản markdown chưa cho tùy chỉnh kích cỡ, tuy vậy nếu bạn dùng thẻ img trực tiếp của HTML thì có thể làm đc, thậm chí chỉ định đc align v.v...

**Comment by ghost** [comment]
chưa nắm rõ cách làm lắm, bạn có thể gửi mình 1 đoạn code dc k?

Vào 16:01 Ngày 14 tháng 07 năm 2016, Orakaro notifications@github.com đã
viết:

**Comment by orakaro** [comment]
VD bạn có thể viết thẳng vào editor như thế này

``` html
<img src="https://github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/under-the-hood-f201a3edb6ec5fd91203f2a310a60a6e.gif" width="200" align="right">
```

Result:
<img src="https://github-atom-io-herokuapp-com.global.ssl.fastly.net/assets/under-the-hood-f201a3edb6ec5fd91203f2a310a60a6e.gif" width="200" align="right">
