### ISSUE TITLE
Search is not working?

### ISSUE THREAD

**Issue by quannt** [Kipalog/Issue-tracker#3]
Như title, đây là bug hay là do Kipalog chưa implement search vậy?

Thanks

**Comment by orakaro** [comment]
Thanks bạn - Đây là feature sắp-được-release . Bạn đợi 1 thời gian ngắn nữa nhé !

**Comment by orakaro** [comment]
Tính năng search đã được release bạn @quannt nhé :+1:

**Comment by quannt** [comment]
:+1:
