### ISSUE TITLE
Where is forgot password feature?

### ISSUE THREAD

**Issue by dhieugo** [Kipalog/Issue-tracker#4]
Hi,

I forgot my password but i can not find "forgot password" link in your page.
Please guide me if i'm missing anything.

**Comment by hnq90** [comment]
Bạn contact anh @huydx để được reset password bằng tay nhé :trollface:

**Comment by dhieugo** [comment]
@huydx help me, please

**Comment by dhieugo** [comment]
:+1: for forgot password

**Comment by huydx** [comment]
@dhieugo em len gitter pm anh de anh reset password bang tay nhe =))

**Comment by dhieugo** [comment]
Cái này chưa xài bao giờ. Đã lên gitter rồi nhưng chưa biết pm thế nào.

**Comment by dhieugo** [comment]
username là dhieugo at gmail dot com

**Comment by huydx** [comment]
@dhieugo already pm you at gitter, take a look ;)
