### ISSUE TITLE
Emoji popup

### ISSUE THREAD

**Issue by ghost** [Kipalog/Issue-tracker#5]
Emoji popup không xuất hiện.

![kipalog-emioji-popup](https://cloud.githubusercontent.com/assets/1160426/10331091/a2f7ef34-6cfc-11e5-9d3b-1f56370ef3c6.png)

```
Google Chrome 47.0.2522.1 dev (64-bit)
```

**Comment by orakaro** [comment]
Cái này hơi khó, do màn hình đang không đủ dài nên cái bảng không tìm được chỗ hiện lên. Anh cũng muốn sửa nhưng phải chọc vào framework Semantic UI nên chưa đc :(
Còn để khắc phục ngay thì em cho màn hình dài ra là okie :smile:
