### ISSUE TITLE
[UX] Auto focus on first input when start new topic

### ISSUE THREAD

**Issue by J2TEAM** [Kipalog/Issue-tracker#7]
Như tiêu đề, mình góp ý về việc thêm "autofocus" vào input của Tiêu đề khi [viết bài mới](http://kipalog.com/posts/new)!

![image](https://cloud.githubusercontent.com/assets/5250117/10337269/d20ece6a-6d28-11e5-8f04-acd17202f4cf.png)

**Comment by orakaro** [comment]
Many thanks ! This is improved !
