### ISSUE TITLE
Validate profile picture URL

### ISSUE THREAD

**Issue by J2TEAM** [Kipalog/Issue-tracker#8]
Người dùng vẫn có thể lưu dù input không phải URL (ảnh) hợp lệ.

![untitled](https://cloud.githubusercontent.com/assets/5250117/10338119/59d815e0-6d2e-11e5-9f23-be0d6274a594.gif)

**Comment by orakaro** [comment]
Many thanks ! This is fixed !

**Comment by J2TEAM** [comment]
@DTVD what about this? :grinning: 

`<input type="url" pattern="^https?:\/\/.+\/.+\.(jpg|jpeg|png)$" />`

**Comment by orakaro** [comment]
Hi @J2TeaM 

Bản sửa của Kipalog hiện tại (frontend) chỉ accept đường link thực sự hiện được thành ảnh, vì vậy mình nghĩ là cover tốt hơn dùng regex. Cảm ơn ý kiến của bạn :+1:
