### ISSUE TITLE
[UX] Auto align center images on article

### ISSUE THREAD

**Issue by J2TEAM** [Kipalog/Issue-tracker#9]
Hình ảnh nên tự động căn giữa trong bài viết (như [Ghost](https://ghost.org/)).

![image](https://cloud.githubusercontent.com/assets/5250117/10708791/a356318a-7a3e-11e5-81c1-fe374a8b49e8.png)

**Comment by orakaro** [comment]
Thanks ! Hình ảnh đã được chỉnh lại cân giữa !
